# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quote_option.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 613)
        Form.setStyleSheet("")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(20, 40, 80, 37))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(20, 100, 80, 15))
        self.label2.setObjectName("label2")
        self.info_stream = QtWidgets.QTextBrowser(Form)
        self.info_stream.setGeometry(QtCore.QRect(730, 40, 271, 561))
        self.info_stream.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.info_stream.setObjectName("info_stream")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 10, 72, 15))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(650, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(840, 10, 72, 15))
        self.label_4.setObjectName("label_4")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 270, 711, 331))
        self.graphicsView.setObjectName("graphicsView")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 150, 75, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(260, 150, 48, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(360, 150, 40, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(460, 150, 32, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(550, 150, 40, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(660, 150, 24, 15))
        self.label_10.setObjectName("label_10")
        self.subscribeButton = QtWidgets.QPushButton(Form)
        self.subscribeButton.setGeometry(QtCore.QRect(10, 10, 93, 21))
        self.subscribeButton.setObjectName("subscribeButton")
        self.cancel_subscribe_Button = QtWidgets.QPushButton(Form)
        self.cancel_subscribe_Button.setGeometry(QtCore.QRect(120, 10, 93, 21))
        self.cancel_subscribe_Button.setObjectName("cancel_subscribe_Button")
        self.buy_one = QtWidgets.QLineEdit(Form)
        self.buy_one.setGeometry(QtCore.QRect(250, 40, 110, 31))
        self.buy_one.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.buy_one.setObjectName("buy_one")
        self.buy_one2 = QtWidgets.QLineEdit(Form)
        self.buy_one2.setGeometry(QtCore.QRect(250, 90, 110, 31))
        self.buy_one2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.buy_one2.setObjectName("buy_one2")
        self.sell_one = QtWidgets.QLineEdit(Form)
        self.sell_one.setGeometry(QtCore.QRect(370, 40, 110, 31))
        self.sell_one.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.sell_one.setObjectName("sell_one")
        self.sell_one2 = QtWidgets.QLineEdit(Form)
        self.sell_one2.setGeometry(QtCore.QRect(370, 90, 110, 31))
        self.sell_one2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.sell_one2.setObjectName("sell_one2")
        self.newprice = QtWidgets.QLineEdit(Form)
        self.newprice.setGeometry(QtCore.QRect(490, 40, 110, 31))
        self.newprice.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.newprice.setObjectName("newprice")
        self.newprice2 = QtWidgets.QLineEdit(Form)
        self.newprice2.setGeometry(QtCore.QRect(490, 90, 110, 31))
        self.newprice2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.newprice2.setObjectName("newprice2")
        self.iv_1 = QtWidgets.QLineEdit(Form)
        self.iv_1.setGeometry(QtCore.QRect(130, 170, 91, 31))
        self.iv_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.iv_1.setObjectName("iv_1")
        self.iv_2 = QtWidgets.QLineEdit(Form)
        self.iv_2.setGeometry(QtCore.QRect(130, 210, 91, 31))
        self.iv_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.iv_2.setObjectName("iv_2")
        self.delta_1 = QtWidgets.QLineEdit(Form)
        self.delta_1.setGeometry(QtCore.QRect(230, 170, 91, 31))
        self.delta_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.delta_1.setObjectName("delta_1")
        self.delta_2 = QtWidgets.QLineEdit(Form)
        self.delta_2.setGeometry(QtCore.QRect(230, 210, 91, 31))
        self.delta_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.delta_2.setObjectName("delta_2")
        self.gamma_1 = QtWidgets.QLineEdit(Form)
        self.gamma_1.setGeometry(QtCore.QRect(330, 170, 91, 31))
        self.gamma_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.gamma_1.setObjectName("gamma_1")
        self.gamma_2 = QtWidgets.QLineEdit(Form)
        self.gamma_2.setGeometry(QtCore.QRect(330, 210, 91, 31))
        self.gamma_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.gamma_2.setObjectName("gamma_2")
        self.vega_1 = QtWidgets.QLineEdit(Form)
        self.vega_1.setGeometry(QtCore.QRect(430, 170, 91, 31))
        self.vega_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.vega_1.setObjectName("vega_1")
        self.vega_2 = QtWidgets.QLineEdit(Form)
        self.vega_2.setGeometry(QtCore.QRect(430, 210, 91, 31))
        self.vega_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.vega_2.setObjectName("vega_2")
        self.theta_1 = QtWidgets.QLineEdit(Form)
        self.theta_1.setGeometry(QtCore.QRect(530, 170, 91, 31))
        self.theta_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.theta_1.setObjectName("theta_1")
        self.theta_2 = QtWidgets.QLineEdit(Form)
        self.theta_2.setGeometry(QtCore.QRect(530, 210, 91, 31))
        self.theta_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.theta_2.setObjectName("theta_2")
        self.rho_1 = QtWidgets.QLineEdit(Form)
        self.rho_1.setGeometry(QtCore.QRect(630, 170, 91, 31))
        self.rho_1.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.rho_1.setObjectName("rho_1")
        self.rho_2 = QtWidgets.QLineEdit(Form)
        self.rho_2.setGeometry(QtCore.QRect(630, 210, 91, 31))
        self.rho_2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.rho_2.setObjectName("rho_2")
        self.security_du = QtWidgets.QLineEdit(Form)
        self.security_du.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.security_du.setStyleSheet("background-color:rgb(255, 85, 0);\\ncolor: rgb(255, 255, 255)")
        self.security_du.setObjectName("security_du")
        self.security_du2 = QtWidgets.QLineEdit(Form)
        self.security_du2.setGeometry(QtCore.QRect(10, 210, 111, 31))
        self.security_du2.setStyleSheet("background-color:rgb(255, 85, 0);\\ncolor: rgb(255, 255, 255)")
        self.security_du2.setObjectName("security_du2")
        self.security_ID = QtWidgets.QLineEdit(Form)
        self.security_ID.setGeometry(QtCore.QRect(120, 40, 119, 31))
        self.security_ID.setStyleSheet("background-color:rgb(255, 85, 0);\\ncolor: rgb(255, 255, 255)")
        self.security_ID.setObjectName("security_ID")
        self.security_ID2 = QtWidgets.QLineEdit(Form)
        self.security_ID2.setGeometry(QtCore.QRect(120, 90, 119, 31))
        self.security_ID2.setStyleSheet("background-color:rgb(255, 85, 0);\\ncolor: rgb(255, 255, 255)")
        self.security_ID2.setObjectName("security_ID2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(510, 10, 80, 15))
        self.label_11.setObjectName("label_11")
        self.volume = QtWidgets.QLineEdit(Form)
        self.volume.setGeometry(QtCore.QRect(610, 40, 110, 31))
        self.volume.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.volume.setObjectName("volume")
        self.volume2 = QtWidgets.QLineEdit(Form)
        self.volume2.setGeometry(QtCore.QRect(610, 90, 110, 31))
        self.volume2.setStyleSheet("background-color:rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255)")
        self.volume2.setObjectName("volume2")
        self.info_stream.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label1.raise_()
        self.label2.raise_()
        self.label_4.raise_()
        self.graphicsView.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.subscribeButton.raise_()
        self.cancel_subscribe_Button.raise_()
        self.buy_one.raise_()
        self.buy_one2.raise_()
        self.sell_one.raise_()
        self.sell_one2.raise_()
        self.newprice.raise_()
        self.newprice2.raise_()
        self.iv_1.raise_()
        self.iv_2.raise_()
        self.delta_1.raise_()
        self.delta_2.raise_()
        self.gamma_1.raise_()
        self.gamma_2.raise_()
        self.vega_1.raise_()
        self.vega_2.raise_()
        self.theta_1.raise_()
        self.theta_2.raise_()
        self.rho_1.raise_()
        self.rho_2.raise_()
        self.security_du.raise_()
        self.security_du2.raise_()
        self.security_ID.raise_()
        self.security_ID2.raise_()
        self.label_11.raise_()
        self.volume.raise_()
        self.volume2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.security_ID, self.security_ID2)
        Form.setTabOrder(self.security_ID2, self.subscribeButton)
        Form.setTabOrder(self.subscribeButton, self.cancel_subscribe_Button)
        Form.setTabOrder(self.cancel_subscribe_Button, self.buy_one)
        Form.setTabOrder(self.buy_one, self.buy_one2)
        Form.setTabOrder(self.buy_one2, self.sell_one)
        Form.setTabOrder(self.sell_one, self.sell_one2)
        Form.setTabOrder(self.sell_one2, self.newprice)
        Form.setTabOrder(self.newprice, self.newprice2)
        Form.setTabOrder(self.newprice2, self.volume)
        Form.setTabOrder(self.volume, self.volume2)
        Form.setTabOrder(self.volume2, self.info_stream)
        Form.setTabOrder(self.info_stream, self.security_du)
        Form.setTabOrder(self.security_du, self.security_du2)
        Form.setTabOrder(self.security_du2, self.iv_1)
        Form.setTabOrder(self.iv_1, self.iv_2)
        Form.setTabOrder(self.iv_2, self.delta_1)
        Form.setTabOrder(self.delta_1, self.delta_2)
        Form.setTabOrder(self.delta_2, self.gamma_1)
        Form.setTabOrder(self.gamma_1, self.gamma_2)
        Form.setTabOrder(self.gamma_2, self.vega_1)
        Form.setTabOrder(self.vega_1, self.vega_2)
        Form.setTabOrder(self.vega_2, self.theta_1)
        Form.setTabOrder(self.theta_1, self.theta_2)
        Form.setTabOrder(self.theta_2, self.rho_1)
        Form.setTabOrder(self.rho_1, self.rho_2)
        Form.setTabOrder(self.rho_2, self.graphicsView)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "SecurityID"))
        self.label2.setText(_translate("Form", "SecurityID"))
        self.label.setText(_translate("Form", "买一价"))
        self.label_2.setText(_translate("Form", "卖一价"))
        self.label_3.setText(_translate("Form", "成交量"))
        self.label_4.setText(_translate("Form", "信息流"))
        self.label_5.setText(_translate("Form", "隐含波动率"))
        self.label_6.setText(_translate("Form", "Delta"))
        self.label_7.setText(_translate("Form", "Gamma"))
        self.label_8.setText(_translate("Form", "Vega"))
        self.label_9.setText(_translate("Form", "Theta"))
        self.label_10.setText(_translate("Form", "Rho"))
        self.subscribeButton.setText(_translate("Form", "订阅"))
        self.cancel_subscribe_Button.setText(_translate("Form", "取消订阅"))
        self.security_ID.setText(_translate("Form", "10001771.SH"))
        self.security_ID2.setText(_translate("Form", "10001751.SH"))
        self.label_11.setText(_translate("Form", "最新成交价"))

